Module5 task2
htmlacademy-ecmascript/1805765-big-trip-15 pull request #6
Opened 2021-09-05 13:57 UTC by nicolas-ivanov

2021-09-07 01:39 UTC, Epsilonnnn requested changes

2021-09-07 01:39 UTC, Epsilonnnn commented on src/presenter/point.js
> +  destroy() {
в таких методах важно не забыть очистить все ресурсы, тут сейчас не все ресурсы, которые использует презентер очищаются

2021-09-07 01:39 UTC, Epsilonnnn commented on src/presenter/point.js
> +    this._changeMode();
эта ф-ция вызывается не на каждую смену режима, нужно более понятное название

думаю вызов самой ф-ции стоит унести выше, так как есть 2 отзеркаливющих друг-друга метода, которые больше про логику отображения, чем про что-то еще

2021-09-07 01:39 UTC, Epsilonnnn commented on src/utils/common.js
> +export const updateItem = (items, update) => {
кажется эта ф-ция более специфичная и подходит только для конкретного презентера, но не для всего проекта (в теле ф-ции делается конкретное предположение, что каждый итем объект и имеет поле `id`), поэтому стоит унести ее из utils

2021-09-07 01:39 UTC, Epsilonnnn commented on src/utils/common.js
> +  return [
чем вызван именно такой способ обновления одной точки через пересоздание массива целиком?

2021-09-07 01:39 UTC, Epsilonnnn commented on src/view/point-create.js
> +export default class NewPointForm extends AbstractView {
для чего этот компонент?

2021-09-07 01:39 UTC, Epsilonnnn commented on src/view/sorting.js
> +      <input id="sort-day" class="trip-sort__input  visually-hidden" type="radio" name="trip-sort" value="sort-day">
ты уже выделил константы, стоит использовать их и в разметке

2021-09-07 01:39 UTC, Epsilonnnn commented on src/view/sorting.js
> +
форматирование

2021-09-07 01:39 UTC, Epsilonnnn commented on src/view/sorting.js
> +    return `<form class="trip-events__trip-sort  trip-sort" action="#" method="get">
для чего это сделано через форму?

2021-09-09 12:31 UTC, nicolas-ivanov commented on src/view/trip-info.js
> +  </section>`;
Подскажи, плиз, что конкретно здесь не так?

Комментарий в целом по форматированию: у меня подключен конфиг eslint-config-htmlacademy и линтер срабатывает при каждом сохранении файла, поэтому вроде не должно быть расхождений с рекомендованным стилем.

2021-09-09 12:32 UTC, nicolas-ivanov commented on src/view/sorting.js
> +export default class SortingView extends AbstractView{
Да, пробела не хватает?

2021-09-09 12:36 UTC, nicolas-ivanov commented on src/utils/date.js
> +
Fixed

2021-09-09 12:36 UTC, nicolas-ivanov commented on src/main.js
> +render(siteHeaderElement, new TripInfoView(generatedPoints).getElement(), RenderPosition.AFTERBEGIN);
Fixed

2021-09-09 12:40 UTC, nicolas-ivanov commented on src/mock/point.js
> +    id: nanoid(),
Насколько я понимаю, в следующих домашках эта функция будет использовать не только для стабов, но и для новых объектов типа TripPoint. Делал по аналогии с демонстрационным заданием: https://github.com/htmlacademy-ecmascript/taskmanager-15/pull/5/files#diff-abcd29fb9a2807f9614245deb3a6d4ae05d75bfb908fdac1eaad872d8305a6a5R67

2021-09-09 12:59 UTC, nicolas-ivanov commented on src/utils/date.js
> +import dayjs from 'dayjs';
Ок, перенес generateDatePair() в date.js
Остальные импорты dayjs оставил на месте, поскольку мне кажется излишним придумывать обертки для понятных однострочных функций, так как эта, например:

```
export const sortByDays = (pointA, pointB) => dayjs(pointA.startTime).diff(dayjs(pointB.startTime));
```
Что думаешь?

2021-09-09 13:00 UTC, nicolas-ivanov commented on src/view/abstract.js
> +export default class Abstract {
Ок, а как стоит назвать? AbstractComponent? Мы же его используем для самых разных сущностей - TripList, Point, etc., то есть это достаточно универсальный класс.

2021-09-09 13:02 UTC, nicolas-ivanov commented on src/view/trip-info.js
> +    let [startTime, endTime] = [null, null];
Переписал на две строчки

2021-09-09 13:15 UTC, nicolas-ivanov commented on src/view/point-edit.js
> +    this.getElement().querySelector('.event__rollup-btn').addEventListener('click', this._clickHandler);
Ок, что нужно для этого сделать? Сохранять куда-то тип ивента и ссылку на хэндлер? Нашел такой ответ на 
https://stackoverflow.com/a/53267116/1712419

В демонстрационном задании, насколько я понял, колбеки не удалялись: https://github.com/htmlacademy-ecmascript/taskmanager-15/pull/4/files#diff-95e5a3c5c9e293e178f29f60330bc53dee50f0cd1c91a2d16510a5cbda24f6f8R25

2021-09-09 13:17 UTC, nicolas-ivanov commented on src/presenter/point.js
> +  destroy() {
А что еще нужно почистить?

2021-09-09 13:24 UTC, nicolas-ivanov commented on src/presenter/point.js
> +    this._changeMode();
> эта ф-ция вызывается не на каждую смену режима, нужно более понятное название

Поясни, плиз, почему не на каждую смену режима? Разве есть еще режимы, кроме Default и Editing?

> думаю вызов самой ф-ции стоит унести выше, так как есть 2 отзеркаливющих друг-друга метода, которые больше про логику отображения, чем про что-то еще

Ты имеешь в виду, что _replaceCardToForm и _replaceFormToCard лучше посместить после init()?

2021-09-09 13:27 UTC, nicolas-ivanov commented on src/utils/common.js
> +export const updateItem = (items, update) => {
Ок, унес ее в presenter/trip.js

2021-09-09 13:29 UTC, nicolas-ivanov commented on src/utils/common.js
> +  return [
Так сделано в демонстрационном задании: https://github.com/htmlacademy-ecmascript/taskmanager-15/pull/5/files#diff-e449682db7451062b66fbbfc1e886bff9b68907f3a5cc2acb4ffb8d0c3d487c6R17

2021-09-09 13:30 UTC, nicolas-ivanov commented on src/view/point-create.js
> +export default class NewPointForm extends AbstractView {
Убрал буду использовать EditTripPointFormView для создания новых компонентов точек маршрута.

2021-09-09 13:35 UTC, nicolas-ivanov commented on src/view/sorting.js
> +      <input id="sort-day" class="trip-sort__input  visually-hidden" type="radio" name="trip-sort" value="sort-day">
Done

2021-09-09 13:36 UTC, nicolas-ivanov commented on src/view/sorting.js
> +
Fixed

2021-09-10 09:00 UTC, Epsilonnnn commented on src/mock/point.js
> +    id: nanoid(),
ага, хорошо, понял

2021-09-10 09:02 UTC, Epsilonnnn commented on src/presenter/point.js
> +  destroy() {
есть еще pointsListContainer, стоит ссылку на него обнулить, потому что дом-элементы удаляются из памяти только тогда, когда они удалены из дом и в js-коде на них нет ссылок

2021-09-10 09:03 UTC, Epsilonnnn commented on src/presenter/point.js
> +    this._changeMode();
имею ввиду changeMode перенести в _handleEditClick

2021-09-10 09:04 UTC, Epsilonnnn commented on src/view/abstract.js
> +export default class Abstract {
да, можно так `AbstractComponent`

все сущности, для которых он используется, принадлежат к одной области - все они компоненты

2021-09-10 09:06 UTC, Epsilonnnn commented on src/view/trip-info.js
> +  </section>`;
я просто тут заметил, что строчка за закрывающую фигурную скобку выходит, когда должен быть отступ, но в целом если линтер не ругается, то ничего страшного

2021-09-10 09:18 UTC, Epsilonnnn commented on src/utils/date.js
> +import dayjs from 'dayjs';
тут опять же дело в упорядоченности, если каждый раз импортировать dayjs и по новому что-то реализовывать, то это будет приводить к дублированию ф-циональности, особенно если это будет большой проект, где много файлов и мало кто будет смотреть на то как используется dayjs где-то еще кроме date.js, чтобы выносить общие ф-ции, поэтому я бы предложил придерживаться конвеншена, что все ф-ции с датами в date.js. Да где-то это может показаться избыточным, но это позволит сохранять четкую структуру кода, которая важнее, так как в дальнейшем позволит разрабатывать проект легче.

Поэтому тут бы хотелось в date.js иметь ф-цию которая получает на вход две даты и выдает дифф

для sortByTime хотелось бы иметь ф-цию, которая принимает на фход дату и выдает часы из нее

2021-09-10 09:20 UTC, Epsilonnnn commented on src/view/point-edit.js
> +    this.getElement().querySelector('.event__rollup-btn').addEventListener('click', this._clickHandler);
у тебя уже есть ссылка на обработчик события (в данном случае _clickHandler) и ты знаешь куда навешивал этот обработчик, поэтому нужно просто с того место где он был навешан его удалить в методе removeElement

2021-09-10 13:51 UTC, nicolas-ivanov commented on src/view/trip-info.js
> +  </section>`;
Понял, ок!

2021-09-10 13:56 UTC, nicolas-ivanov commented on src/view/abstract.js
> +export default class Abstract {
Понял, поправил

2021-09-10 14:18 UTC, nicolas-ivanov commented on src/view/point-edit.js
> +    this.getElement().querySelector('.event__rollup-btn').addEventListener('click', this._clickHandler);
Ок, сделал в point.js, point-edit.js и sorting.js, проверь, пожалуйста.

2021-09-10 14:33 UTC, nicolas-ivanov commented on src/presenter/point.js
> +  destroy() {
Ок, поправил

2021-09-10 14:57 UTC, nicolas-ivanov commented on src/presenter/point.js
> +    this._changeMode();
Пока не понял, зачем там делать. Что происходит внутри ChangeMode:

```
this._pointPresenter.forEach((presenter) => presenter.resetView());
```
Это нужно делать всегда, когда карточка точки меняется на форму (закрываем все остальные формы, если они были открыты).

2021-09-10 15:05 UTC, nicolas-ivanov commented on src/utils/date.js
> +import dayjs from 'dayjs';
Ок, поправил

2021-09-13 18:11 UTC, Epsilonnnn approved these changes

2021-09-15 08:15 UTC, merged