Module6 task1
htmlacademy-ecmascript/1805765-big-trip-15 pull request #7
Opened 2021-09-06 16:41 UTC by nicolas-ivanov

2021-09-20 10:28 UTC, Epsilonnnn requested changes

2021-09-20 10:28 UTC, Epsilonnnn commented on src/view/point-edit.js
> +      const newSubmitBtn = createElement(`<button class="event__save-btn  btn  btn--blue" type="submit" ${this._isSubmitEnabled ? '' : 'disabled'}>Save</button>`);
это нужно делать через перерисовку элемента, данные для изменения статуса нужно брать из данных (this._data), но не из инпутов

флоу должен выглядеть так:
1. Меняются данные
2. Триггерится перерисовка элемента
3. Во время перерисовки из this._data берутся данные для того чтобы выяснить как отобразить кнопку
4. Кнопка отрисовывается в шаблоне нужным статусом

При таком флоу логика с версткой останется в одном методе, где она и  должна быть, при этом будет четкая и последовательная связь между данными и отображением - отображение зависит от данных, отображение меняется тогда, когда меняются данные

2021-09-20 10:28 UTC, Epsilonnnn commented on src/view/point-edit.js
> +          ${cities.map((city) => (`<option value="${  city.name  }"></option>`)).join('')}
нужен единый стиль форматирования, на это в том числе будут смотреть при защите

2021-09-26 15:05 UTC, nicolas-ivanov commented on src/view/trip-info.js
> +      ${ getTotalPrice(this._tripPoints) }
Можешь, пожалуйста, пояснить, как здесь нужно было написать?

2021-09-26 15:26 UTC, nicolas-ivanov commented on src/view/point-edit.js
> +      const newSubmitBtn = createElement(`<button class="event__save-btn  btn  btn--blue" type="submit" ${this._isSubmitEnabled ? '' : 'disabled'}>Save</button>`);
В целом - да, флоу должен быть такой, однако здесь особый случай - мы хотим дисейблить кнопку еще до сабмита, а именно, если данные хотя бы в одном инпуте отсутствуют или невалидные. В этом случае данные не получится взять из `this._data`, их там еще нет.

2021-09-26 15:27 UTC, nicolas-ivanov commented on src/view/point-edit.js
> +          ${cities.map((city) => (`<option value="${  city.name  }"></option>`)).join('')}
Я пока не особо понимаю, как именно мне нужно поправить эту строку и какие стили форматирования бывают.

2021-09-26 15:31 UTC, Epsilonnnn commented on src/view/trip-info.js
> +      ${ getTotalPrice(this._tripPoints) }
в одних местах пишется`${ data }`, в других `${data}`

2021-09-26 15:32 UTC, Epsilonnnn commented on src/view/point-edit.js
> +      const newSubmitBtn = createElement(`<button class="event__save-btn  btn  btn--blue" type="submit" ${this._isSubmitEnabled ? '' : 'disabled'}>Save</button>`);
по хорошему для этого нужно на onChange каждого инпута изменять данные, например так делается в реакте, но давай тут оставим так

2021-09-26 15:32 UTC, Epsilonnnn commented on src/view/point-edit.js
> +          ${cities.map((city) => (`<option value="${  city.name  }"></option>`)).join('')}
то же что и тут - https://github.com/htmlacademy-ecmascript/1805765-big-trip-15/pull/7#discussion_r716221111

2021-09-26 15:33 UTC, nicolas-ivanov commented on src/view/point-edit.js
> +      const newSubmitBtn = createElement(`<button class="event__save-btn  btn  btn--blue" type="submit" ${this._isSubmitEnabled ? '' : 'disabled'}>Save</button>`);
Понял, ок!

2021-09-26 15:38 UTC, nicolas-ivanov commented on src/view/trip-info.js
> +      ${ getTotalPrice(this._tripPoints) }
Понял, с твоего позволения поправлю это позже, иначе сейчас будут многочисленные конфликты со следующими коммитами.

2021-09-26 15:41 UTC, merged